### ISSUE TITLE
wrong WordLevelTimestamps with streaming (startContinuousRecognitionAsync)

### ISSUE THREAD

**Issue by vcombey** [microsoft/cognitive-services-speech-sdk-js#564]
I am using the timstamp to display the transcription synced with the audio I record. You can see an exemple of the final object here https://spoke.app/share/4n5kfvpyu1db7x9czm6rj083wasge2hq?all.

When you start playing the audio you will see the current word in blue.
they ared synced with the audio.
But if you go to the middle of the video you will see an offset of ~ 3 words.

I am using the code copy pasted from: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js where i request wordLevelTimestamp

the basic MediaRecorder. : https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

The bug appear on last version of chrome and firefox on MacOs and android. ( the platform I tested )

This is a hard blocker for us to use the api.
I am suprised to not find any reference of this issue as this is very basic use of the sdk.

Many thanks

**Comment by glharper** [comment]
@vcombey Thank you for using Speech SDK, and writing this issue up. So for your use case, you are recognizing a predetermined audio stream, then playing it back and highlighting each word based on the wordLevelTimestamp from the previous recognition session?

(I'm framing my question this way because there will be an obvious lag between sending the audio and getting the recognition result if you're attempting to highlight each word in realtime.)

**Comment by vcombey** [comment]
Wow no, I realize that my description is really not clear at all.

I'm recording the default microphone via 
`        const microphone_stream = await navigator.mediaDevices.getUserMedia({ audio: true }`
    ```
const options = { mimeType: 'audio/wav', 
    new MediaRecorder(microphone_stream!, options)
```
and parallel to that transcribing the default microphone with:
        ```
audioConfig = SpeechSDK.AudioConfig.fromStreamInput(microphone_stream)
  ...
    const reco = SpeechSDK.SpeechRecognizer.FromConfig(speechConfig, audioConfig);
    reco.startContinuousRecognitionAsync()
```

I calculate an initial offset to synchronize the start of the recognition job with the start of the recording job. 
I add this offset to each wordTimestamp:
```
        const start_record_offset: AUDIO_CONTEXT.currentTime,
         MEDIA_RECORDER.start(3000)
```

```
    const start_transcribe_offset = AUDIO_CONTEXT.currentTime
    const reco = await doContinuousRecognition(spokeSession, stream)
```
```

   const offset = spokeSession.start_transcribe_offset -        spokeSession.start_record_offset
	const newWords = words.map(w => ({
                ...w,
                ts: w.ts + offset,
                end_ts: w.end_ts + offset,
    })
```


and the result is what you can see here: https://spoke.app/share/4n5kfvpyu1db7x9czm6rj083wasge2hq?all

the words in the first sentences have a correct timestamp but as you advance in the video the timestamps are more and more incorrect.

it would be like if the sample rate of the microphone was different from the one expected by the api

Is it clearer ?

**Comment by glharper** [comment]
> it would be like if the sample rate of the microphone was different from the one expected by the api.

That could actually be the issue...any idea what the sample rate of the microphone in this case was?
For mediaStream inputs, the samplesPerSecond is fixed at 16K in the SDK, and the bitsPerSample to 16.

If the incoming mic audio source has a different sample rate than that, you'll have to create a push or pullAudioInputStream input for AudioConfig.fromStreamInput() instead of a MediaStream input, as the push/pull streams allow you to specify the sample rate (and bitsPerSample).

Let me know if this avenue of inquiry sounds promising and I'll dig out some push stream sample code.

**Comment by vcombey** [comment]
It may be that but I tested setting the sampleRate with:
`  AUDIO_CONTEXT = new AudioContext({ sampleRate: 16000 })`
and
```
         MICROPHONE_STREAM = await navigator.mediaDevices.getUserMedia({
             audio: {
                sampleRate: 16000,
             }
         })
```

and the bug persist,
Maybe the bitsPerSample is incorrect, I don't know how to check that.

I'm open to try using pullAudioInputStream input if you have an exemple with a microphone.

**Comment by glharper** [comment]
The code to check the actual sample rate and sample size:
        const tracks = mediastream.getAudioTracks();
        const settings = tracks[0].getSettings();
        console.log(`media track settings: rate: ${settings.sampleRate}, bits per sample: ${settings.sampleSize}, channelCount: ${settings.channelCount}`);
        
I spent the afternoon discovering that the mediaRecorder API is a dead-end for using a push, and will test using the Web Audio API for grabbing data that I can convert to PCM instead.  Here is the general pattern to use for creating and updating the pushAudioInputStream with a mediaStream:
```
        const tracks = mediastream.getAudioTracks();
        const settings = tracks[0].getSettings();
        
        const format = SpeechSDK.AudioStreamFormat.getWaveFormat(settings.sampleRate, settings.sampleSize, settings.channelCount, SpeechSDK.AudioFormatTag.PCM); //ALAW and MULAW should also work
        const p = SpeechSDK.AudioInputStream.createPushStream(format);

        // write to push stream when data is available
        recorder.on("data", { //DOESN'T WORK FOR MediaRecorder API
          // convert data to arrayBuffer format
          p.write(dataInArrayBufferFormat);
        });

        // close pushStream when data stops
        recorder.on("stop", {
          console.log("stop event");
          tracks[0].stop();
          p.close();
        };

        var audioConfig  = SpeechSDK.AudioConfig.fromStreamInput(p);
        recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
```
Hope this demonstrates push stream usage, I believe push stream will accept wav data in PCM, aLaw, or muLaw, and set proper wav headers for audio using those codecs. Not sure off the top of my head what other codecs the Speech service accepts.

**Comment by vcombey** [comment]
Hi thank you for your answer.

I tested out the code you sent, my microphone is effectively in 48khz.
I also tested with the microphone of my Bluetooth headset which is 16khz and it works.

So you're right, the sampling rate it the problem. But I don't know either how we could re-sample the audio on the fly before sending it.

I found that example which seems promising but the person said it doesn't work:
https://jtuto.com/16bit-16khz-monochannel-wav-format-audio-streaming-with-javascript/

Is it the right direction?



Thanks.

**Comment by glharper** [comment]
@vcombey Yes, this feels like the right direction. Thank you for that initial comment about sample rates, that really accelerated finding the source for this issue. 

[Here is one example](https://typedarray.org/from-microphone-to-wav-with-getusermedia-and-web-audio/) that I would look at for resampling the audio on the fly. Since the input/output is mono, you can ignore the dual channel parsing and subsequent interleaving, and you may not need a gain node either.

If you could update this issue with the code you end up using, I can look at incorporating that in the SDK itself for better result accuracy. (Or feel free to open a PR with a new API if you'd like to go a step further. :-)

**Comment by vcombey** [comment]
How to ignore the dual data channel parsing and interleaving ?

I tried with just that:


```
        const tracks = stream.getAudioTracks()
        const settings = tracks[0].getSettings()
        const format = SpeechSDK.AudioStreamFormat.getWaveFormat(settings.sampleRate!, settings.sampleSize!, (settings as any).channelCount, SpeechSDK.AudioFormatTag.PCM); //ALAW and MULAW should also work
        const p = SpeechSDK.AudioInputStream.createPushStream(format);
        const context = new AudioContext()
        const sampleRate = context.sampleRate;
        const audioInput = context.createMediaStreamSource(stream);
        const bufferSize = 4096;
        const recorder = context.createScriptProcessor(bufferSize, 1, 1)
        audioInput.connect(recorder);
        recorder.onaudioprocess = function(e) {

            const inputData = e.inputBuffer.getChannelData(0);
            for (let i = 0; i < inputData.length; i++) {
                const multiplier = inputData[i] < 0 ? 0x8000 : 0x7fff; // 16-bit signed range is -32768 to 32767
                view.setInt16(i * 2, (inputData[i] * multiplier) | 0, true); // index, value, little edian
            }
            p.write(buffer);
     }
     
```
without luck,
The api is responding language: "unknown" indefinitely.

I also tried the same code + adding the wav header, and it produce the same result.
I don't know if this hader is mandatory and if I must include on the first packet or on every chunk I send to the api.

```           
            const buffer = new ArrayBuffer(44 + recordingLength * 2);
            const view = new DataView(buffer);

            // write the WAV container, check spec at: https://ccrma.stanford.edu/courses/422/projects/WaveFormat/

            // RIFF chunk descriptor

            writeUTFBytes(view, 0, "RIFF");

            view.setUint32(4, 44 + interleaved.length * 2, true);

            writeUTFBytes(view, 8, "WAVE");

            // FMT sub-chunk

            writeUTFBytes(view, 12, "fmt ");

            view.setUint32(16, 16, true);

            view.setUint16(20, 1, true);

            // mono (1 channels)

            view.setUint16(22, 1, true);

            view.setUint32(24, sampleRate, true);

            view.setUint32(28, sampleRate * 4, true);

            view.setUint16(32, 4, true);

            view.setUint16(34, 16, true);

            // data sub-chunk

            writeUTFBytes(view, 36, "data");
            view.setUint32(40, interleaved.length * 2, true);
```

I think this issue is too deep for me, I don't have the competence nor the time to fix it.

**Comment by vcombey** [comment]
I successfuly used a pullAudioInputStream with a 16kh pcm data stream,
Sadly the bug persist and it has exactly the same behavior.
I think we took a wrong direction

here is the code: 
        const p = SpeechSDK.AudioInputStream.createPushStream(format);


        const recorder = new RecordRTC(stream, {
            type: 'audio',
            mimeType: 'audio/webm;codecs=pcm', // endpoint requires 16bit PCM audio
            recorderType: StereoAudioRecorder,
            timeSlice: 250, // set 250 ms intervals of data that sends to AAI
            desiredSampRate: 16000,
            numberOfAudioChannels: 1, // real-time requires only one channel
            bufferSize: 4096,
            audioBitsPerSecond: 128000,
            ondataavailable: (blob) => {
                console.log('data available')
                const reader = new FileReader();
                reader.onload = () => {
                    const base64data = reader.result;

                    // audio data must be sent as a base64 encoded string
                    console.log('typeofdata', typeof (base64data))
                    if (base64data) {
                        const data = _base64ToArrayBuffer((base64data as string).split('base64,')[1] as string)
                        p.write(data)
                    }
                };
                reader.readAsDataURL(blob);
            },
        });

        recorder.startRecording();

**Comment by glharper** [comment]
> desiredSampRate: 16000,
> audioBitsPerSecond: 128000,

What happens when you set these to match the incoming audio sample rate and bits per second (making sure that the "format" variable also matches in the incoming audio sample rate and bits per sample)?

**Comment by vcombey** [comment]
hum it appear the offset is far less.
From my tests it is 1 word / 3 minutes instead of 5+ words / 3 minutes

**Comment by glharper** [comment]
@vcombey if you could send me a standalone web page demonstrating this issue, I can test and see if matching the mediastream sample rate in the SDK will help mitigate it. Or I can generate a binary with a naive fix and send it to you for testing. In the meantime, is a 1 word per 3 minute lag acceptable? Not sure what other workarounds exist.

**Comment by glharper** [comment]
No recent activity, closing.

**Comment by SMaurischat** [comment]
@glharper and general reference: I am seeing a comparable issue in our application since the last versions of chromium based browsers, which leads to distorted sample rates (you can also see the websocket sending less chunks/second from second 30 onwards). 
using AudioConfig.fromDefaultMicrophoneInput(); 

Schuld be solved in future chromium versions: https://bugs.chromium.org/p/chromium/issues/detail?id=1381319&q=component%3ABlink%3EWebAudio&can=2
