### ISSUE TITLE
[Bug]: 3D Blendshape Data Not Generating for Super Realistic Voices

### ISSUE THREAD

**Issue by jillbourque** [microsoft/cognitive-services-speech-sdk-js#816]
### What happened?

The 3D Blendshape SSML function for the Super Realistic Voices seems to be broken. It was working until about a month ago. When we send an SSML request we get audio but no 3D Blendshape data for these voices:

**"Super Realistic" Voices NOT Sending 3D Blendshapes**
en-US-EmmaNeural - NOT Sending TTS 3D Blendshape Data
en-US-AndrewNeural - NOT Sending TTS 3D Blendshape Data

Yet, these "regular" voices are still correctly sending blendshape data:

**These "Regular" Voices ARE sending 3D Blendshapes** 
en-US-JennyNeural - Sending TTS 3D Blendshape Data Correctly
en-US-NancyNeural - Sending TTS 3D Blendshape Data Correctly
en-US-SteffanNeural - Sending TTS 3D Blendshape Data Correctly

**Blog on Super Realistic Voices**
https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/introducing-super-realistic-ai-voices-optimized-for/ba-p/3933744

### Version

1.36.0 (Latest)

### What browser/platform are you seeing the problem on?

Chrome

**Comment by yulin-li** [comment]
Hi, the blendshape support for these voices is being added. We will update this issue when it goes live.

**Comment by peterpanseu** [comment]
Hi @jillbourque, the problem has been fixed and now the realistic voices can support 3D Blendshape. Please have a try.

**Comment by jillbourque** [comment]
> Hi @jillbourque, the problem has been fixed and now the realistic voices can support 3D Blendshape. Please have a try.

Hi @peterpanseu and @yulin-li 

I tested and Emma is now working but Andrew is still not working. 

I have tested with the following results:

**NOT Sending TTS 3D Blendshape Data**
en-US-AndrewNeural

**Sending TTS 3D Blendshape Data Correctly**
en-US-AndrewMultilingualNeural
en-US-JennyNeural
en-US-NancyNeural
en-US-SteffanNeural
en-US-EmmaNeural
en-US-EmmaMultilingualNeural 
en-US-AvaNeural 
en-US-AvaMultilingualNeural 
en-US-BrianNeural
en-US-BrianMultilingualNeural 
en-US-GuyNeural 
en-US-AriaNeural 
en-US-DavisNeural 
en-US-JaneNeural
en-US-JasonNeural 
en-US-SaraNeural 
en-US-TonyNeural
en-US-AmberNeural 
en-US-AnaNeural 
en-US-AshleyNeural  
en-US-BrandonNeural
en-US-AIGenerate1Neural

**Comment by peterpanseu** [comment]
@jillbourque could you please try a different text? It could be that the text you used for testing AndrewNeural has been used previously and the problematic result has been cached. By using a new text, it will be a new synthesis using the newly deployed voice. In the test on our side, AndrewNeural can return BlendShape data. Please have a try.

**Comment by jillbourque** [comment]
Hi @peterpanseu Ah, yes! Now it is working correctly.

**Comment by jillbourque** [comment]
Thank you!

**Comment by peterpanseu** [comment]
My pleasure.

**Comment by Richa10729837** [comment]
> My pleasure.

@peterpanseu thank you for support. @jillbourque I appreciate your cooperation!!

**Comment by stevecox1964** [comment]
An example code run

Speech synthesis completed.
Viseme 0 at 50.0 ms BlendShape 
Viseme 7 at 100.0 ms BlendShape
Viseme 6 at 212.5 ms BlendShape 
Viseme 6 at 287.5 ms BlendShape 
Viseme 6 at 387.5 ms BlendShape 
Viseme 0 at 700.0 ms BlendShape 
Viseme 0 at 0.0 ms BlendShape {"FrameIndex":0,"BlendShapes":[[0.171,0.164,0.038,0, <snip>
